In [ ]:
# load data 
from sklearn.datasets import load_iris

iris = load_iris()

In [ ]:
# tipe data numpy array

X, y = iris.data, iris.target

print(X[:5])
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [ ]:
# tipe data pandas dataframe
import pandas as pd

df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target

df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [ ]:
# membuat pipeline

from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

# pipeline numpy array
pipe_numpy = make_pipeline(StandardScaler(), LinearSVC(dual='auto'))

# pipeline pandas dataframe
pipe_pandas = make_pipeline(StandardScaler(), LinearSVC(dual='auto'))

In [ ]:
# Training
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# split data
# numpy 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=46)

# pandas dataframe
df_train, df_test = train_test_split(df, test_size=0.2, random_state=46)

In [ ]:
# training

# numpy 
pipe_numpy.fit(X_train, y_train)

y_pred = pipe_numpy.predict(X_test)

print('Hasil evaluasi model numpy')
print(classification_report(y_test, y_pred))


# pandas dataframe
X_train_df, y_train_df = df_train.drop('target', axis=1), df_train['target']
X_test_df, y_test_df = df_test.drop('target', axis=1), df_test['target']

pipe_pandas.fit(X_train_df, y_train_df)

y_pred_pandas = pipe_pandas.predict(X_test_df)

print('Hasil evaluasi model pandas')
print(classification_report(y_test_df, y_pred_pandas))

Hasil evaluasi model numpy
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.88      0.78      0.82         9
           2       0.80      0.89      0.84         9

    accuracy                           0.90        30
   macro avg       0.89      0.89      0.89        30
weighted avg       0.90      0.90      0.90        30

Hasil evaluasi model pandas
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.88      0.78      0.82         9
           2       0.80      0.89      0.84         9

    accuracy                           0.90        30
   macro avg       0.89      0.89      0.89        30
weighted avg       0.90      0.90      0.90        30



In [ ]:
# save model
import pickle

# numpy 
with open('model_numpy.pkl', 'wb') as model_file:
    pickle.dump(pipe_numpy, model_file)

# pandas 
with open('model_pandas.pkl', 'wb') as model_file:
    pickle.dump(pipe_pandas, model_file)

In [ ]:
# load model

# numpy
with open('model_numpy.pkl', 'rb') as model_file:
    loaded_numpy_model = pickle.load(model_file)

In [ ]:
# prediksi

new_data_numpy = [[1,1,1,1]]

loaded_numpy_model.predict(new_data_numpy)

array([1])

In [ ]:
# cek label 
iris.target_names

['setosa' 'versicolor' 'virginica']


In [ ]:
# pandas
with open('model_pandas.pkl', 'rb') as model_file:
    loaded_pandas_model = pickle.load(model_file)

In [ ]:
# prediksi

new_data_pandas = [[1,1,1,1]]

new_data_pd = pd.DataFrame(new_data_pandas, columns=iris.feature_names)

loaded_pandas_model.predict(new_data_pd)

array([1])

In [ ]:
new_data_pd

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  1                 1                  1                 1


In [ ]:
iris.feature_names

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
